// 單字資料庫（可於此檔案增修單字，格式：['英文','中文']）
const VOCAB_RAW = [
    ['like','喜歡；像'],['sport','運動'],['much','多（的）'],['team','隊；組'],['practice','練習'],['every','每一'],['then','那麼'],['swim','游泳'],['join','參加'],['eye','眼睛'],['hair','頭髮'],['know','知道；認識'],['hundred','百'],['centimeter','公分'],['You can say that again!','一點也沒錯！'],['guitar','吉他'],['piano','鋼琴'],['fly a kite','放風箏'],['paint','畫圖；油漆'],['make a cake','做蛋糕'],['nose','鼻子'],['leg','腿'],['large','大的'],['ear','耳朵'],['mouth','嘴巴'],['thick','厚的'],['lip','嘴唇'],['strong','強壯的'],['arm','手臂'],['height','身高；高度'],['player','選手；球員'],['the USA','美國'],['body','身體'],["put one’s all",'盡全力'],['into','到…裡面'],['a lot of','很多的'],['stand out','突出'],['different','不同的'],['top','頂尖的'],['on the other hand','另一方面'],['make up for…','彌補…'],
    ['early','早的'],['work','工作'],['often','經常'],['get up','起床'],['usually','通常'],['seldom','很少'],['sometimes','有時候'],['even','甚至'],['late','晚的'],["do one’s homework",'做功課'],['hour','小時'],['always','總是'],['tired','疲累的'],['shower','淋浴'],['never','從未'],['by the way','順帶一提'],['library','圖書館'],['check out','借（書）'],['once','一次'],['twice','兩次'],['walk','溜（寵物）'],["I can’t help it.",'我沒辦法。／我控制不了。'],['then','然後'],['too','太…'],['How often…?','多常…？'],['about','大約'],["brush one’s teeth",'刷牙'],['face','臉'],['breakfast','早餐'],['lunch','午餐'],['exercise','運動'],['computer','電腦'],['minute','分鐘'],['answer','回答；答案'],['question','問題'],['trouble','困難；麻煩'],['life','生命；生活'],['love','愛'],['real','真實的'],
    ['painting','畫作'],['flower','花'],['which','哪一個'],['thirsty','口渴的'],['coffee','咖啡'],['shop','商店'],['later','稍後；晚點'],['Of course.','當然。'],['clerk','店員'],['may','可以；可能'],['juice','果汁'],['want','想要'],['anything','任何事物'],['else','其他'],['treat','請客；款待'],['sweet','甜美的；甜的'],['hot','熱的'],['chocolate','巧克力'],['dollar','元'],['for here','內用'],['to go','外帶'],['Here you are.','給你。'],['bright','鮮豔的；明亮的'],['dark','黑的；暗的'],['art','美術；藝術'],['milk','牛奶'],['hamburger','漢堡'],['chicken rice','雞肉飯'],['tea','茶'],['ice cream','冰淇淋'],['soup','湯'],['sandwich','三明治'],['work','作品'],['show','表現；秀出'],['part','部分'],['sky','天空'],['street','街道'],['by','被；由'],
    ['why','為什麼'],['wear','戴；穿'],['mask','口罩；面具'],['because','因為'],['sick','生病的'],['water','水'],['glass','玻璃杯；玻璃'],['flour','麵粉'],['need','需要；需求'],['pie','派'],['still','仍然'],['thing','東西；事情'],['a little','一點點'],['salt','鹽'],['something','某物；某事'],['sugar','糖'],['get','取得'],['all right','好吧；好的'],['so','所以'],['back off','退後；走開'],['meal','餐'],['bottle','瓶子'],['candy','糖果'],['popcorn','爆米花'],['cup','杯'],['bowl','碗'],['fruit salad','水果沙拉'],['pizza','披薩'],['milk shake','奶昔'],['can','罐子'],['toast','烤土司；烘烤'],['bread','麵包'],['yummy','好吃的'],['easy','容易的'],['snack','點心'],['kid','小孩'],['cheese','起司'],['plate','盤子'],['last','最後（的）'],['enjoy','享受；喜愛'],['turn into','（使）變成'],['each','每一個（的）'],
    ['yesterday','昨天'],['beach','海灘'],['trash','垃圾'],['ago','前；以前'],['visit','拜訪'],['island','島嶼'],['a few','幾個；一些'],['sea','海'],['stop','停止'],['happen','發生'],['dead','死亡的'],['warm','溫暖的'],['rainforest','雨林'],['die','死亡'],['by','在…旁邊'],['How come?','怎麼會？／為什麼？'],['then','那時候'],['busy','忙碌的'],['river','河流'],['lake','湖泊'],['hill','山丘'],['mountain','山'],['camp','露營；紮營'],['climb','爬（山）'],['row a boat','划船'],['plant','種植；植物'],['hike','健行'],['picnic','野餐'],['last','上一個的'],['live','居住'],['playground','遊樂場；操場'],['everything','每樣事物'],['change','改變'],['burn','燃燒'],['oil','油'],['sell','賣'],['make money','賺錢'],['miss','想念'],['little','小的'],['little by little','一點一點地；逐漸地'],['way','方式'],
    ['airport','機場'],['travel','旅行；行進'],['rest','休息'],['hotel','飯店'],['plane','飛機'],['the sights','風景；名勝'],['bookstore','書店'],['buy','購買'],['just','就；只'],['learn','學習'],['story','故事'],['cool','酷的'],['train','火車'],['cold','冷的'],['try','嘗試'],['way','距離；路線'],['take','帶；拿；取'],['the other day','前幾天'],['station','車站；局'],['department store','百貨公司'],['restaurant','餐廳'],['theater','電影院'],['market','市場'],['temple','寺廟'],['famous','有名的'],['during','在…期間'],['besides','除…之外'],['fall in love','墜入情網'],['age','年紀'],['lose','失去'],['cry','哭泣'],['hide','躲藏'],['build','建造'],['trip','旅行；行程'],['sadly','令人傷心地'],['last','持續']
  ];
